info_homepage:
    path:     /
    defaults: { _controller: InfoBundle:Default:index }

info_contact:
    path:     /contact
    defaults: { _controller: InfoBundle:Default:contact }

info_service:
    path:     /service
    defaults: { _controller: InfoBundle:Default:service }

info_about:
    path:     /about
    defaults: { _controller: InfoBundle:Default:about }